# Site settings
author: Gabriela johnson
title: 
header-img: img/home-bg.png
email: johnsongabriela12@gmail.com
copyright_name: Gabriela johnson
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  GabrielaJustine16

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
